/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacao;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.UIManager;

/**
 *
 * @author kelwin.rodrigues
 */
public class Terminal extends javax.swing.JFrame {

    Conta conta1;
    Conta conta2;
    
    /**
     * Creates new form Terminal
     */
    public Terminal() {
        initComponents();
        
        
        conta1 = new Conta(1, 123, "Kelwin", 5000, 2000);
        conta2 = new Conta(1, 456, "José", 1500, 2000);
        
        imprimeConta();
       
    }
    
    public void imprimeConta(){
       try{
            lblConta2.setText(conta1.getNomePessoa());
            if(conta1.getSaldo() >= 0){
                lblSaldo2.setForeground(new java.awt.Color(67, 160, 71));
            }else{
                lblSaldo2.setForeground(new java.awt.Color(244, 81, 30));
            }
            lblSaldo2.setText(Tools.formatarValor(conta1.getSaldo(), true));
            
            lblConta4.setText(conta2.getNomePessoa());
            if(conta2.getSaldo() >= 0){
                lblSaldo4.setForeground(new java.awt.Color(67, 160, 71));
            }else{
                lblSaldo4.setForeground(new java.awt.Color(244, 81, 30));
            }
            lblSaldo4.setText(Tools.formatarValor(conta2.getSaldo(), true));
        
        }catch(Exception ex){
            System.err.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnConta1 = new javax.swing.JPanel();
        lblConta1 = new javax.swing.JLabel();
        btnSacar1 = new javax.swing.JButton();
        txtValor1 = new javax.swing.JTextField();
        lblSaldo1 = new javax.swing.JLabel();
        lblConta2 = new javax.swing.JLabel();
        lblSaldo2 = new javax.swing.JLabel();
        btnDepositar1 = new javax.swing.JButton();
        btnTransferir1 = new javax.swing.JButton();
        jpnConta2 = new javax.swing.JPanel();
        lblConta3 = new javax.swing.JLabel();
        btnSacar2 = new javax.swing.JButton();
        txtValor2 = new javax.swing.JTextField();
        lblSaldo3 = new javax.swing.JLabel();
        lblConta4 = new javax.swing.JLabel();
        lblSaldo4 = new javax.swing.JLabel();
        btnDepositar2 = new javax.swing.JButton();
        btnTransferir2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnConta1.setBorder(javax.swing.BorderFactory.createTitledBorder("CONTA 1"));

        lblConta1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConta1.setText("Conta:");

        btnSacar1.setText("Sacar");
        btnSacar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacar1ActionPerformed(evt);
            }
        });

        lblSaldo1.setText("Saldo:");

        lblConta2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConta2.setText("nome");

        lblSaldo2.setText("R$");

        btnDepositar1.setText("Depositar");
        btnDepositar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositar1ActionPerformed(evt);
            }
        });

        btnTransferir1.setText("Transferir");
        btnTransferir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnConta1Layout = new javax.swing.GroupLayout(jpnConta1);
        jpnConta1.setLayout(jpnConta1Layout);
        jpnConta1Layout.setHorizontalGroup(
            jpnConta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnConta1Layout.createSequentialGroup()
                .addGroup(jpnConta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnConta1Layout.createSequentialGroup()
                        .addGroup(jpnConta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaldo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblConta1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnConta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSaldo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblConta2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnConta1Layout.createSequentialGroup()
                        .addComponent(btnSacar1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDepositar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTransferir1)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jpnConta1Layout.setVerticalGroup(
            jpnConta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnConta1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnConta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnConta1Layout.createSequentialGroup()
                        .addComponent(lblConta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSaldo1))
                    .addGroup(jpnConta1Layout.createSequentialGroup()
                        .addComponent(lblConta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSaldo2)))
                .addGap(18, 18, 18)
                .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnConta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSacar1)
                    .addGroup(jpnConta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDepositar1)
                        .addComponent(btnTransferir1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jpnConta2.setBorder(javax.swing.BorderFactory.createTitledBorder("CONTA 2"));

        lblConta3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConta3.setText("Conta:");

        btnSacar2.setText("Sacar");
        btnSacar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacar2ActionPerformed(evt);
            }
        });

        lblSaldo3.setText("Saldo:");

        lblConta4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConta4.setText("nome");

        lblSaldo4.setText("R$");

        btnDepositar2.setText("Depositar");
        btnDepositar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositar2ActionPerformed(evt);
            }
        });

        btnTransferir2.setText("Transferir");
        btnTransferir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnConta2Layout = new javax.swing.GroupLayout(jpnConta2);
        jpnConta2.setLayout(jpnConta2Layout);
        jpnConta2Layout.setHorizontalGroup(
            jpnConta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnConta2Layout.createSequentialGroup()
                .addGroup(jpnConta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnConta2Layout.createSequentialGroup()
                        .addGroup(jpnConta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaldo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblConta3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnConta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSaldo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblConta4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnConta2Layout.createSequentialGroup()
                        .addComponent(btnSacar2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDepositar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTransferir2)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jpnConta2Layout.setVerticalGroup(
            jpnConta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnConta2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnConta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnConta2Layout.createSequentialGroup()
                        .addComponent(lblConta3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSaldo3))
                    .addGroup(jpnConta2Layout.createSequentialGroup()
                        .addComponent(lblConta4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSaldo4)))
                .addGap(18, 18, 18)
                .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnConta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSacar2)
                    .addGroup(jpnConta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDepositar2)
                        .addComponent(btnTransferir2)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnConta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnConta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnConta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnConta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacar1ActionPerformed
        // TODO add your handling code here:     
        try{
            double valor = Double.parseDouble(txtValor1.getText());
            boolean operacao = conta1.sacar(valor);
            if(operacao == true){
                //saque deu certo
                CaixaDeDialogo.obterinstancia().exibirMensagem("Saque Realizado", 'i');
            }else{
                //saque não realizado
                CaixaDeDialogo.obterinstancia().exibirMensagem("Saque Não Realizado", 'e');
            }

            imprimeConta();
            
        }catch(Exception ex){
            System.err.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_btnSacar1ActionPerformed

    private void btnSacar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacar2ActionPerformed
        // TODO add your handling code here:
        try{
            double valor = Double.parseDouble(txtValor2.getText());
            boolean operacao = conta2.sacar(valor);
            if(operacao == true){
                //saque deu certo
                CaixaDeDialogo.obterinstancia().exibirMensagem("Saque Realizado", 'i');
            }else{
                //saque não realizado
                CaixaDeDialogo.obterinstancia().exibirMensagem("Saque Não Realizado", 'e');
            }

            imprimeConta();
            
        }catch(Exception ex){
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnSacar2ActionPerformed

    private void btnDepositar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositar1ActionPerformed
        // TODO add your handling code here:
       try{
        double valor = Double.parseDouble(txtValor1.getText());
        conta1.deposito(valor);
        
        imprimeConta();
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnDepositar1ActionPerformed

    private void btnDepositar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositar2ActionPerformed
        // TODO add your handling code here:
        try{
        double valor = Double.parseDouble(txtValor2.getText());
        conta2.deposito(valor);
        
        imprimeConta();
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnDepositar2ActionPerformed

    private void btnTransferir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferir1ActionPerformed
        // TODO add your handling code here:
       double valor = Double.parseDouble(txtValor1.getText());
           conta1.sacar(valor);
           conta2.deposito(valor);
            imprimeConta();
            /*double valor = Double.parseDouble(txtValor1.getText());
        conta1.sacar(valor);
        
        imprimeConta();*/
        
            
     
        
    }//GEN-LAST:event_btnTransferir1ActionPerformed

    private void btnTransferir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferir2ActionPerformed
        // TODO add your handling code here:
        double valor = Double.parseDouble(txtValor2.getText());
           conta2.sacar(valor);
           conta1.deposito(valor);
            imprimeConta();
        
        
    }//GEN-LAST:event_btnTransferir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try {
            UIManager.setLookAndFeel( new FlatDarkLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
                       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Terminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepositar1;
    private javax.swing.JButton btnDepositar2;
    private javax.swing.JButton btnSacar1;
    private javax.swing.JButton btnSacar2;
    private javax.swing.JButton btnTransferir1;
    private javax.swing.JButton btnTransferir2;
    private javax.swing.JPanel jpnConta1;
    private javax.swing.JPanel jpnConta2;
    private javax.swing.JLabel lblConta1;
    private javax.swing.JLabel lblConta2;
    private javax.swing.JLabel lblConta3;
    private javax.swing.JLabel lblConta4;
    private javax.swing.JLabel lblSaldo1;
    private javax.swing.JLabel lblSaldo2;
    private javax.swing.JLabel lblSaldo3;
    private javax.swing.JLabel lblSaldo4;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
